### ISSUE TITLE
Demande en lecture seule (adapter les écrans) (DEV_42597)

### ISSUE THREAD

**Issue by apeclattecost** [TecostNetwork/Network#105]
Lorsqu'on est dans un contexte de demande, si celle-ci est clôturée ou annulée, on ne doit pas pouvoir modifier les champs.
Tous les securityButtons doivent être grisés également, comme si l'on avait pas l'accès en écriture.

A voir, plusieurs possibilités : 
- on peut s'inspirer du SIC qui a une annotation @RequiresMto avec des paramètres sur l'état de la MTO (fermée, ouverte...)
- on peut faire une simple annotation sur le même principe que @RequiresOpenRequestOrApplicant qui permet de vérifier qu'on a soit une demande ouverte, soit qu'on est pas dans le contexte d'une demande. Par ex: les données personnelles ou allergies seraient éditables via le contexte bénéficiaire, mais pas depuis le contexte de la demande fermée.
- on peut simplement vérifier que la demande est ouverte ou qu'il n'y en a pas dans le contexte actuel.

Les vérifications sont à implémenter (probablement) dans le SecurityChecker.
- les securityButtons vérifient automatiquement via le securityChecker
- pour les champs éditables directement dans les écrans il faudra faire la vérification à la main via un helper getHasWritingRights() sur le contrôleur.

**Comment by maximewicht** [comment]
le nouvel attribut `writeCheck` de l'annotation `@Security` permet d'indiquer une règle supplémentaire pour que les tags `sipres:securityXXX` soit activés.
La règle `RequestWritableChecker` a été implémentée à titre d'exemple

Nouveaux composants:
> `sipres:securityAutoComplete`
> `sipres:securityInputText`
> `sipres:securitySelectOneRadio`
> `sipres:securitySelectOneMenu`


Il reste à adapter les écrans en question et d'implémenter correctement le

**Comment by apeclattecost** [comment]
- Attention il y avait un inputTextArea qui avait été remplacé par un securityInputText dans EditClosingRequest. Du coup ça donne un tout petit champ au lieu du champ multiligne.
- Attention aussi pas mal de composants appelaient #{unController.isDisabledRequest} alors qu'il suffisait d'utiliser le securityComponent. 
![image](https://user-images.githubusercontent.com/74962829/123622693-d504c980-d80c-11eb-9caa-de92f74c0ce6.png)
- Et d'autres composants de type securityComponent utilisent quand même la propriété du controleur ce qui est dommage car on perd le denialType 
![image](https://user-images.githubusercontent.com/74962829/123622535-9ff87700-d80c-11eb-996f-03ab5036413a.png)


- [ ] Ajouter le composant securitySelectManyCheckbox
- [ ] L'utiliser dans EditClosingRequest à la place du p:selectManyCheckbox qui reste
