### ISSUE TITLE
Confirmation utilisateur pour sauvegarde - Partie 2 Adapter les écran

### ISSUE THREAD

**Issue by apeclattecost** [TecostNetwork/Network#106]
Dans les contextes bénéficiaire et demande : 
- s'il y a des champs éditables directement dans la page
- et s'ils ont été modifiés (à voir comment faire, via un javascript ?)
demander à l'utilisateur s'il faut sauvegarder ou non lorsqu'il quitte la page.

Pour la sauvegarde, il faut que chaque vue ou chaque fragment puisse spécifier quelles méthodes appeler.
Si aucune méthode n'est spécifiée, le contrôle est entièrement désactivé

**Comment by maximewicht** [comment]
### Utilisation
Placer le composant `<sipres:leaveListener />` dans votre page xhtml (à côté du composant `<sipres:toolbarDelegate />` est un bon endroit :) )

Placer ce code d'initialisation dans le `enter()` d'un contrôleur principal, *avant l'appel à `BottomToolbar.initToolbar(...)`* :

> `LeaveListenerComponent.setupListener(
>                 callback(this::hasUnsavedChanges),
>                 callback(this::validate),
>                 callback(this::doSave));`

Implémenter les méthodes validate, doSave et hasUnsavedChanges. Vous pouvez les nommer les méthodes comme vous le voulez.

Voir la javadoc de `LeaveListenerComponent` pour plus de détails

### Ecrans à migrer

- [ ] `EditApplicantFieldsGroup`
- [ ] `EditApplicantInformations`
- [ ] `EditClosingRequest`
- [ ] `EditRequestInformations`
- [ ] `ViewDecisions`
- [ ] `ViewInstitutionFieldsGroup`
- [ ] `ViewInstitutionPreference`
- [ ] `ViewRecommandations`
- [ ] `ViewSetUpDecisions`
- [ ] `ManageApplicantProfiling`

Quand vous pensez avoir tout migré, décommenter les premières lignes de `ch.tecost.sipres.web.layout.BottomToolbar.initToolbar(ZeroMethodExpr, ZeroMethodExpr, BottomToolbarControlState...)`
