### ISSUE TITLE
Bug applicant context après création

### ISSUE THREAD

**Issue by apeclattecost** [TecostNetwork/Network#137]
Lorsqu'on crée un applicant, le contexte se charge automatiquement mais les écrans indiquent qu'on a pas les droits.

Pour reproduire : 
- Depuis la liste des bénéficiaires, créer un applicant
- Le contexte s'ouvre automatiquement
- L'écran indique qu'il n'y a pas les droits (il faut pas se connecter en super donc :-))

**Comment by maximewicht** [comment]
Scénario non reproductible. A explorer
