### ISSUE TITLE
Retour montée de version - Notification à double

### ISSUE THREAD

**Issue by joe-tecost** [TecostNetwork/Network#350]
Premier point des retours de la montée de version. Certaine notification concernant les soumissions ont l'air d'être envoyées plusieurs fois pour une même action. 

Il me semble que le problème existe depuis un moment sur Network et ne date pas forcément de la montée de version,  à creuser.

**Comment by mjlassitecost** [comment]
Je n'ai pas trouvé comment ce cas peut arriver.
Par contre, il y avait un problème de notifications doubles concernant les données administratives du bénéficiaire que j'ai corrigé.

**Comment by joe-tecost** [comment]
Des tests approfondis dans la card #357 permettront de peut-être déceler le problème souligné dans cette card
