### ISSUE TITLE
DEV_39093 Contexte d'une demande

### ISSUE THREAD

**Issue by apeclattecost** [TecostNetwork/Network#60]
Mettre au point le contexte de la demande, c'est-à-dire le fait d'afficher une demande et tous ses menus dans le menu principal, en sachant qu'on travaille sur celle-ci. Similaire au principe du contexte bénéficiaire.

- Adapter le menu
- Adapter le bandeau ?
- Définir une annotation @RequiresRequest ?
- à discuter

**Comment by joe-tecost** [comment]
Oublie pas de diminuer la complexité
